services:
- type: web
  name: next-js
  runtime: node
  plan: starter
  buildCommand: npm; npm run build
  startCommand: npm start
  autoDeploy: false
  envVars:
  - key: NODE_ENV
    value: production
 - type: web
   name: nextjs-static
   runtime: static
   buildCommand: npm; npm run build
   staticPublishPath: build
   envVars:
   - key: NODE_ENV
     value: production
